---
title: "Hexbin chart with the hexbin package"
descriptionMeta: "This post explains how to build a hexbin chart with R using the hexbin package. Hexbin chart is a 2d density chart, allowing to visualize the relationship between 2 numeric variables."
descriptionTop: "This post explains how to build a hexbin chart with R using the `hexbin` package. Hexbin chart is a [2d density chart](2d-density-chart.html), allowing to visualize the relationship between 2 numeric variables."
sectionText: "2d density section"
sectionLink: "2d-density-chart.html"
DataToVizText: "Data to Viz"
DataToVizLink: "data-to-viz.com/graph/density2d.html"
url: "100-high-density-scatterplot-with-binning"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 100px">




<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

[Scatterplots](scatterplot.html) can get very hard to interpret when displaying large datasets, as points inevitably overplot and can???t be individually discerned.

Binning can be though of as a two-dimensional [histogram](histogram.html), where shades of the bins take the place of the heights of the bars. This technique is computed in the `hexbin` package.

This example has been published by [Myles Harrison](http://www.everydayanalytics.ca/2014/09/5-ways-to-do-2d-histograms-in-r.html) on R-bloggers.

</div>


<div class = "col-md-6  col-sm-12">

```{r thecode, echo=FALSE, out.width = "100%", fig.height=7}
# Packages
library(hexbin)
library(RColorBrewer)
 
# Create data
x <- rnorm(mean=1.5, 5000)
y <- rnorm(mean=1.6, 5000)
 
# Make the plot
bin<-hexbin(x, y, xbins=40)
my_colors=colorRampPalette(rev(brewer.pal(11,'Spectral')))
plot(bin, main="" , colramp=my_colors , legend=F ) 

```
</div>
</div>



```{r thecode, eval=FALSE}
```
















<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedCorrelation.html")
```
