---
title: "R Snail."
descriptionMeta: "A piece of generative art built by Christophe Cariou with R."
descriptionTop: "A piece of generative art built by Christophe Cariou with R."
sectionText: "ggplot2 Section"
sectionLink: "ggplot2-package.html"
DataToVizText: "About line chart"
DataToVizLink: "data-to-viz.com/graph/line.html"
url: "127-r-snail"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 80px">



<div class = "row">

<div class = "col-md-4  col-sm-12 align-self-center">

Thanks to [Christophe Cariou](http://www.chcariou.fr) for this ” R snail”, also available on the [accidental art](https://twitter.com/accidental__art) twitter page.

</div>


<div class = "col-md-8  col-sm-12">

```{r thecode, echo=FALSE, out.width = "100%", fig.height=7}
par(mfrow=c(1,1),mar=c(0,0,0,0),oma=c(1,1,1,1))
plot(0,0,type="n", xlim=c(-2,32), ylim=c(3,27),
    xaxs="i", yaxs="i", axes=FALSE, xlab=NA, ylab=NA,
    asp=1)

for (j in 0:35) {
for (i in 0:35) {


    R <- 8
    alpha <- j*10
    X <- 15+R*cos(alpha/180*pi)
    Y <- 15+R*sin(alpha/180*pi)

    r <- 3
    beta <- i*10
    x <- 15+r*cos(beta/180*pi)
    y <- 15+r*sin(beta/180*pi)

    d1 <- sqrt((X-x)^2+(Y-y)^2)
    xc <- x
    yc <- y

  n <- 180-atan((Y-y)/(X-x))/pi*180

    alpha2 <- -(0:n)
    theta <- alpha2/180*pi

    b <- d1/(n/180*pi)
    r <- b*theta

    x1 <- xc+r*cos(theta)
    y1 <- yc+r*sin(theta)

    lines(x1,y1, col="black")

    }
}
```

</div>
</div>


```{r thecode, eval=FALSE}
```




<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedEvolution.html")
```
