---
title: "Basic wordcloud in R"
descriptionMeta: "A wordcloud is a visual representation of text data. Learn how to build a basic wordcloud with R and the wordcloud library, with reproducible code provided."
descriptionTop: "A wordcloud is a visual representation of text data. Learn how to build a basic wordcloud with R and the wordcloud library, with reproducible code provided."
sectionText: "Wordcloud section"
sectionLink: "wordcloud.html"
DataToVizText: "Warning"
DataToVizLink: "data-to-viz.com/graph/wordcloud.html"
url: "15-wordcloud"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 100px">





<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

[Wordclouds](wordcloud.html) can be very useful to highlight the main topics in text. 

In R, it can be built using the `wordcloud` package as described below. 

<u>Note</u>: the `wordcloud2` package allows more customizations and is extensively described [here](196-the-wordcloud2-library.html).

<u>Note</u>: this [online tool](https://www.jasondavies.com/wordcloud/#%2F%2Fwww.r-graph-gallery.com%0A) is a good non-programming alternative.


</div>


<div class = "col-md-6  col-sm-12">

```{r thecode, echo=FALSE, out.width = "100%", fig.height=7}
#Charge the wordcloud library
library(wordcloud)
 
#Create a list of words (Random words concerning my work)
a <- c("Cereal","WSSMV","SBCMV","Experimentation","Talk","Conference","Writing", 
   "Publication","Analysis","Bioinformatics","Science","Statistics","Data", 
   "Programming","Wheat","Virus","Genotyping","Work","Fun","Surfing","R", "R",
   "Data-Viz","Python","Linux","Programming","Graph Gallery","Biologie", "Resistance",
   "Computing","Data-Science","Reproductible","GitHub","Script")
 
#I give a frequency to each word of this list 
b <- sample(seq(0,1,0.01) , length(a) , replace=TRUE) 
 
#The package will automatically make the wordcloud ! (I add a black background)
par(bg="black") 
wordcloud(a , b , col=terrain.colors(length(a) , alpha=0.9) , rot.per=0.3 )
```
</div>
</div>



```{r thecode, eval=FALSE}
```














<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedRanking.html")
```
