---
title: "Most basic streamgraph"
descriptionMeta: "This post describes how to build a basic streamgraph using R and the streamgraph package. It provides the reproducible code and explanation."
descriptionTop: "This post describes how to build a basic [streamgraph](streamgraphg.html) using `R` and the `streamgraph` package. It provides the reproducible code and explanation."
sectionText: "Streamgraph section"
sectionLink: "streamgraph.html"
DataToVizText: "Data to Viz"
DataToVizLink: "data-to-viz.com/graph/streamgraph.html"
url: "154-basic-interactive-streamgraph-2"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container">


<center><iframe src="HtmlWidget/streamgraphBasic.html" height="440" width="100%" style="border:none;"></iframe></center>


This post describe the basic use of the `streamgraph` package. Your input needs 3 columns:

- a numeric variable for the X axis. Usually it provides time.
- a numeric variable for the Y axis: this is the variable we are studying
- a categorical variable: each group will be plotted as a distinct shape

The `streamgraph()` function requires those 3 inputs to work.

<u>Note</u>: The `streamgraph` package is a work by xxx. It lives on [github]().

<u>Note</u>: you can save the chart as a html file using the `saveWidget()` function of the `htmlwidgets` package, as suggested in the commented code below.

```{r, eval=FALSE}
# Library
library(streamgraph)
 
# Create data:
data <- data.frame(
  year=rep(seq(1990,2016) , each=10),
  name=rep(letters[1:10] , 27),
  value=sample( seq(0,1,0.0001) , 270)
)
 
# Basic stream graph: just give the 3 arguments
pp <- streamgraph(data, key="name", value="value", date="year", height="300px", width="1000px")
pp 

# save the widget
# library(htmlwidgets)
# saveWidget(pp, file=paste0( getwd(), "/HtmlWidget/streamgraphBasic.html"))
```


</div>



```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedEvolution.html")
```
