---
title: "Control streamgraph offset"
descriptionMeta: "The streamgraph package offers several options concerning the chart offset. This feature has a massive impact on the general appearance. This post provides a description of the options."
descriptionTop: "The streamgraph package offers several options concerning the chart offset. This feature has a massive impact on the general appearance. This post provides a description of the options."
sectionText: "Streamgraph section"
sectionLink: "streamgraph.html"
DataToVizText: "Data to Viz"
DataToVizLink: "data-to-viz.com/graph/streamgraph.html"
url: "155-interactive-streamgraph-change-offset"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container">

<div class="row">

<div class="col-md-4">
<iframe src="HtmlWidget/streamgraphOffset1.html" height="440" width="100%" style="border:none;"></iframe>
</div>

<div class="col-md-4">
<iframe src="HtmlWidget/streamgraphOffset2.html" height="440" width="100%" style="border:none;"></iframe>
</div>

<div class="col-md-4">
<iframe src="HtmlWidget/streamgraphOffset3.html" height="440" width="100%" style="border:none;"></iframe>
</div>

</div>

This post follows the previous [basic streamgraph](154-basic-interactive-streamgraph-2). It shows the effect of the `offset` option that can take 3 values:

- `silhouette`: shapes are displayed on both side of an horizontal axis
- `zero`: displayed on top of the 0 line.
- `expand`: equivalent of a percent stacked area chart: the full height is used to visualize percentages.

<u>Note</u>: The `streamgraph` package is a work by xxx. It lives on [github]().

<u>Note</u>: you can save the chart as a html file using the `saveWidget()` function of the `htmlwidgets` package, as suggested in the commented code below.

```{r, eval=FALSE}
# Library
library(streamgraph)

# Create data:
data <- data.frame(
  year=rep(seq(1990,2016) , each=10),
  name=rep(letters[1:10] , 27),
  value=sample( seq(0,1,0.0001) , length(year))
)

# Type 1 (default)
p1 <- streamgraph(data, key="name", value="value", date="year" , 
    offset="silhouette",
    width="400px", height="300px"
    )
 
# Type 2 
p2 <- streamgraph(data, key="name", value="value", date="year" , 
    offset="zero",
    width="400px", height="300px"
    )
 
# Type 3.
p3 <- streamgraph(data, key="name", value="value", date="year" , 
    offset="expand",
    width="400px", height="300px"
    )

# save the widget
# library(htmlwidgets)
# saveWidget(p1, file=paste0( getwd(), "/HtmlWidget/streamgraphOffset1.html"))
# saveWidget(p2, file=paste0( getwd(), "/HtmlWidget/streamgraphOffset2.html"))
# saveWidget(p3, file=paste0( getwd(), "/HtmlWidget/streamgraphOffset3.html"))
```


</div>



```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedEvolution.html")
```
