---
title: "Streamgraph with dropdown button"
descriptionMeta: "The streamgraph package allows to add a dropdown button that controls which group to highlight. See how to use this option with explanation and reproducible code."
descriptionTop: "The `streamgraph` package allows to add a dropdown button that controls which group to highlight. See how to use this option with explanation and reproducible code."
sectionText: "Streamgraph section"
sectionLink: "streamgraph.html"
DataToVizText: "Data to Viz"
DataToVizLink: "data-to-viz.com/graph/streamgraph.html"
url: "156-interactive-streamgraph-with-legend"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container">



<center><iframe src="HtmlWidget/streamgraphDropdown.html" height="440" width="100%" style="border:none;"></iframe></center>


It is pretty straightforward to add a dropdown button thanks to the `sg_legend()` function. Unlike other `streamgraph()` options, `sg_legend()` is used after the pipe command (`%>%`).
                                                                                    
<u>Note</u>: you can save the chart as a html file using the `saveWidget()` function of the `htmlwidgets` package, as suggested in the commented code below.

```{r, eval=FALSE}
# Library
library(streamgraph)
 
# Create data:
data <- data.frame(
  year=rep(seq(1990,2016) , each=10),
  name=rep(letters[1:10] , 27),
  value=sample( seq(0,1,0.0001) , length(year))
)
 
# Stream graph with a legend
pp <- streamgraph(data, key="name", value="value", date="year", height="300px", width="1000px") %>%
  sg_legend(show=TRUE, label="names: ")
  

# save the widget
# library(htmlwidgets)
# saveWidget(pp, file=paste0( getwd(), "/HtmlWidget/streamgraphDropdown.html"))
```





</div>



```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedEvolution.html")
```
