---
title: "Area chart with base R"
descriptionMeta: "This post describes how to build an area chart using base R and the polygon function. Reproducible code is provided."
descriptionTop: "This post describes how to build an [area chart](area-chart.html) using base R and the `polygon()` function. See the [area chart](area-chart.html) section for a `ggplot2` implementation."
sectionText: "Area chart Section"
sectionLink: "area-chart.html"
DataToVizText: "About area chart"
DataToVizLink: "data-to-viz.com/graph/area.html"
url: "165-basic-area-chart"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container">




# Basic area chart with `plot()` and `polygon()`
***

<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

Base R also allows to build area charts thanks to the `polygon()` function. This function requires 2 inputs: `x` and `y`. 

Note that extreme values of both are added at the beginning and at the end of each vectors to make sure the polygon is closed.

</div>


<div class = "col-md-6  col-sm-12">

```{r thecode, echo=FALSE, out.width = "100%", fig.height=7}
# Create data
data <- data.frame(x=seq(1,10), y=sample(seq(1,15),10))

# Draw line on top
plot(data, col=rgb(0.2,0.1,0.5,0.9), type="o", lwd=3, xlab="", ylab="size",
     pch=20)

# Fill the area
polygon(c(min(data$x), data$x, max(data$x)),
        c(min(data$y), data$y, min(data$y)),
        col=rgb(0.2,0.1,0.5,0.2), border=FALSE)
```


</div>
</div>



```{r thecode, eval=FALSE}
```



















<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedEvolution.html")
```
