---
title: "Proportional symbol map with the Cartography package"
descriptionMeta: "The cartography package is a great alternative to make maps with R. This post explains how to build a bubble map using it, with explanation and reproducible code."
descriptionTop: "The [cartography](https://github.com/riatelab/cartography.html) package is a great alternative to make maps with R. This post explains how to build a [bubble map](bubble-map.html) using it, with explanation and reproducible code."
sectionText: "Bubble map section"
sectionLink: "bubble-map.html"
DataToVizText: "About Maps"
DataToVizLink: "data-to-viz.com/graph/bubblemap.html"
url: "177-map-with-proportional-symbols"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 80px">



<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

The `cartography` package is a very good alternative to the [other tools](bubble-map.html) presented in the gallery for building maps.

It notably allows to:

- display a legend with embedded circles
- add data sources on the bottom of the chart
- show north / south


</div>


<div class = "col-md-6  col-sm-12">

```{r thecode, echo=FALSE, out.width = "100%", fig.height=7}
# Library
library(cartography)
library(sp)

# Upload data attached with the package.
data(nuts2006)
 
# Now we have a geospatial object called nuts2.spdf containing the shape of european regions. We can plot it with the plot function.
# summary(nuts2.spdf)

# We also have a dataframe with information concerning every region.
# head(nuts2.df)
# Both object have a first column "id" that makes the link between them.
 
# Plot Europe
plot(nuts0.spdf, border = NA, col = NA, bg = "#A6CAE0")
plot(world.spdf, col = "#E3DEBF", border = NA, add = TRUE)
plot(nuts0.spdf, col = "#D1914D", border = "grey80",  add = TRUE)
 
# Add circles proportional to the total population
propSymbolsLayer(spdf = nuts0.spdf, df = nuts0.df, 
    var = "pop2008", symbols = "circle", col = "#920000", 
    legend.pos = "right", legend.title.txt = "Total\npopulation (2008)", 
    legend.style = "c")
 
# Add titles, legend...
layoutLayer(title = "Countries Population in Europe", 
    author = "cartography", sources = "Eurostat, 2008", 
    scale = NULL, south = TRUE)
```
</div>
</div>



```{r thecode, eval=FALSE}
```









<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedMap.html")
```
