---
title: "Mirrored histogram in basic R"
descriptionMeta: "This post explains how to build a mirrored histogram in Basic R."
descriptionTop: "A [histogram](https://www.data-to-viz.com/graph/histogram.html) displays the distribution of a numeric variable. This posts explains how to build a mirrored histogram in basic R, without any package. It allows to compare the distribution of 2 variables"
sectionText: "Histogram Section"
sectionLink: "histogram.html"
DataToVizText: "About histogram"
DataToVizLink: "data-to-viz.com/graph/histogram.html"
url: "190-mirrored-histogram.html"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 80px">




<div class = "row">
  
<div class = "col-md-6  col-sm-12 align-self-center">

The mirrored histogram allows to compare the distribution of 2 variables.  

First split the screen with the `par(mfrow())` command. The top histogram needs a `xaxt="n"` statement to discard its X axis. For the second one, inverse the values of the `ylim` argument to flip it upside down. Use the `margin` command to adjust the position of the 2 charts.


</div>

  
<div class = "col-md-6  col-sm-12">

```{r, echo=FALSE, out.width = "100%", fig.height=7}
#Create Data
x1 = rnorm(100)
x2 = rnorm(100)+rep(2,100)
par(mfrow=c(2,1))
 
#Make the plot
par(mar=c(0,5,3,3))
hist(x1 , main="" , xlim=c(-2,5), ylab="Frequency for x1", xlab="", ylim=c(0,25) , xaxt="n", las=1 , col="slateblue1", breaks=10)
par(mar=c(5,5,0,3))
hist(x2 , main="" , xlim=c(-2,5), ylab="Frequency for x2", xlab="Value of my variable", ylim=c(25,0) , las=1 , col="tomato3"  , breaks=10)
```
</div>
</div>


```{r eval=FALSE}
#Create Data
x1 = rnorm(100)
x2 = rnorm(100)+rep(2,100)
par(mfrow=c(2,1))
 
#Make the plot
par(mar=c(0,5,3,3))
hist(x1 , main="" , xlim=c(-2,5), ylab="Frequency for x1", xlab="", ylim=c(0,25) , xaxt="n", las=1 , col="slateblue1", breaks=10)
par(mar=c(5,5,0,3))
hist(x2 , main="" , xlim=c(-2,5), ylab="Frequency for x2", xlab="Value of my variable", ylim=c(25,0) , las=1 , col="tomato3"  , breaks=10)
```


<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedDistribution.html")
```







