---
title: "Hexbin chart and scatterplot with ggplot2"
descriptionMeta: "This post explains how to build a hexbin chart with a scatterplot on top using R and ggplot2. Code and reproducible code provided."
descriptionTop: "This post explains how to build a hexbin chart with a [scatterplot](scatterplot.html) on top using `R` and [ggplot2](ggplot2.html). It is an addition to the page about [2d density plot with ggplot2](2d-density-plot-with-ggplot2.html)."
sectionText: "2d density section"
sectionLink: "2d-density-chart.html"
DataToVizText: "Data to Viz"
DataToVizLink: "data-to-viz.com/graph/density2d.html"
url: "198-scatter-and-density-plot-ggplot2"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 100px">




<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

This plot extends the concepts described in the [2d density chart with ggplot2](2d-density-plot-with-ggplot2.html) document. It simply illustrates that a [scatterplot](scatterplot.html) can be added on top of the 2d density chart.

Thanks [Christian Jacob](http://chrisk91.me/) for this submission.
</div>


<div class = "col-md-6  col-sm-12">

```{r thecode, echo=FALSE, out.width = "100%", fig.height=7}
# library
library(ggplot2) 

# data
sample_data <- data.frame(x_values = 1:100 + rnorm(100,sd=20), y_values = 1:100 + rnorm(100,sd=27)) 

#plot
ggplot(sample_data, aes(x_values, y_values)) +
  stat_density2d(geom="tile", aes(fill = ..density..), contour = FALSE) + 
  geom_point(colour = "white")
```
</div>
</div>



```{r thecode, eval=FALSE}
```
















<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedCorrelation.html")
```
