---
title: "Two Histograms with melt colors"
descriptionMeta: "How to display 2 histograms on the same axis in Basic R."
descriptionTop: "A [histogram](https://www.data-to-viz.com/graph/histogram.html) displays the distribution of a numeric variable. This posts explains how to plot 2 histograms on the same axis in Basic R, without any package."
sectionText: "Histogram Section"
sectionLink: "histogram.html"
DataToVizText: "About histogram"
DataToVizLink: "data-to-viz.com/graph/histogram.html"
url: "2-two-histograms-with-melt-colors"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 80px">




<div class = "row">
  
<div class = "col-md-6  col-sm-12 align-self-center">
[Histogramms](histogram.html) are commonly used in data analysis to observe distribution of variables. A common task in data visualization is to compare the distribution of 2 variables simultaneously.  

Here is a tip to plot 2 histograms together (using the `add` function) with transparency (using the [rgb](https://stat.ethz.ch/R-manual/R-devel/library/grDevices/html/rgb.html) function) to keep information when shapes overlap.

</div>

  
<div class = "col-md-6  col-sm-12">

```{r, echo=FALSE, out.width = "100%", fig.height=7}
#Create data
Ixos=rnorm(4000 , 125 , 30)     
Primadur=rnorm(4000 , 200 , 30) 
 
# First distribution
hist(Ixos, breaks=30, xlim=c(0,300), col=rgb(1,0,0,0.5), xlab="height", 
     ylab="nbr of plants", main="distribution of height of 2 durum wheat varieties" )

# Second with add=T to plot on top
hist(Primadur, breaks=30, xlim=c(0,300), col=rgb(0,0,1,0.5), add=T)

# Add legend
legend("topright", legend=c("Ixos","Primadur"), col=c(rgb(1,0,0,0.5), 
     rgb(0,0,1,0.5)), pt.cex=2, pch=15 )
```
</div>
</div>


```{r eval=FALSE}
#Create data
set.seed(1)
Ixos=rnorm(4000 , 120 , 30)     
Primadur=rnorm(4000 , 200 , 30) 
 
# First distribution
hist(Ixos, breaks=30, xlim=c(0,300), col=rgb(1,0,0,0.5), xlab="height", 
     ylab="nbr of plants", main="distribution of height of 2 durum wheat varieties" )

# Second with add=T to plot on top
hist(Primadur, breaks=30, xlim=c(0,300), col=rgb(0,0,1,0.5), add=T)

# Add legend
legend("topright", legend=c("Ixos","Primadur"), col=c(rgb(1,0,0,0.5), 
     rgb(0,0,1,0.5)), pt.cex=2, pch=15 )
```





<br><br><br>
<u>Note</u>: this is how the figure looks like if groups are drawn one beside each other:
```{r, out.width="80%", fig.align="center"}
par(
  mfrow=c(1,2),
  mar=c(4,4,1,0)
)

hist(Ixos, breaks=30 , xlim=c(0,300) , col=rgb(1,0,0,0.5) , xlab="height" , ylab="nbr of plants" , main="" )
hist(Primadur, breaks=30 , xlim=c(0,300) , col=rgb(0,0,1,0.5) , xlab="height" , ylab="" , main="")
```
 
 
 

<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedDistribution.html")
```







