---
title: "Building a 3D knot wiith R and rgl"
descriptionMeta: "This is an illustration of what is possible to do with R and the rgl library: a 3D knot."
descriptionTop: "This is an illustration of what is possible to do with `R` and the `rgl` library: a 3D knot."
sectionText: "3d Section"
sectionLink: "3d.html"
DataToVizText: "3d: warning"
DataToVizLink: "data-to-viz.com/caveat/3d.html"
url: "20-knot-in-3d"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
rgl::setupKnitr()
```

<div class="container" style="padding-top: 80px">



<div class = "row">

<div class = "col-md-5  col-sm-12 align-self-center">

With the `rgl` package, you can make the image moove and zoom in an out. Find this image in the interactive mode here.




</div>


<div class = "col-md-7  col-sm-12">

<center><iframe src="HtmlWidget/3dknot.html" height="580" width="580" style="border:none;"></iframe></center>


</div>
</div>


```{r}
# Library rgl
library(rgl)

#Choose the size of the image on the output (800,650 to have 800 x 600)
r3dDefaults$windowRect <- c(0,50, 800, 650) 
open3d()

#If you want to put line on the background
#bg3d(sphere = TRUE, color = c("grey", "white"), lit = TRUE, back = "lines" ,lwd=2)

# This is to output a rgl plot in a rmarkdown document
# rgl::setupKnitr()


# plot
bg3d( col=rgb(0.2,0.8,0.5,0.8) )
theta <- seq(0, 2*pi, len = 50)
knot <- cylinder3d(
center = cbind(sin(theta) + 3*sin(2*theta), 2*sin(3*theta), cos(theta) - 2*cos(2*theta)),
e1 = cbind(cos(theta) + 4*cos(2*theta),6*cos(3*theta),sin(theta) + 4*sin(2*theta)),radius = 0.9,closed = TRUE)
shade3d(addNormals(subdivision3d(knot, depth = 2)), col = rgb(0.4,0.2,0.8,0.3))

# To display in an R Markdown document:
# rglwidget()

# save it as png
# snapshot3d( "~/Desktop/#20_portfolio_knot_3D.png", fmt="png")

# To save interactive plot to a file:
htmlwidgets::saveWidget(rglwidget(width = 500, height = 500), 
                        file = "HtmlWidget/3dknot.html",
                        libdir = "libs",
                        selfcontained = FALSE
                        )
```



<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedOther.html")
```
