---
title: "Change line chart color according to Y value"
descriptionMeta: "This post explains how to build a line chart in base R, where the line color is set according to the Y axis value. Reproducible code is provided."
descriptionTop: "This post explains how to build a [line chart](line-plot.html) in base R, where the line color is set according to the Y axis value. Reproducible code is provided."
sectionText: "Line chart Section"
sectionLink: "line-plot.html"
DataToVizText: "About line chart"
DataToVizLink: "data-to-viz.com/graph/line.html"
url: "200-change-color-in-lineplot-following-y-value"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 80px">



<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

The `plotrix` library allows to change the line color according to the value of the Y axis thanks to the `clplot` function. 

Here, the `RColorBrewer` package is used to set a palette of 8 colors.

<u>Note:</u>: Thanks to Carl Witthoft for sending this chart.

</div>


<div class = "col-md-6  col-sm-12">

```{r thecode, echo=FALSE, out.width = "100%", fig.height=6}
# library
library(plotrix)
 
#create color palette
library(RColorBrewer)
my_colors = brewer.pal(8, "Set2") 
 
# Create data
x<-seq(1,100)
y<-sin(x/5)+x/20
 
# Plot x and y
par(mar=c(4,4,2,2))
clplot(x, y, main="", lwd=5, levels=c(1,2,3,4,5), col=my_colors, showcuts=T , bty="n")
```

</div>
</div>


```{r thecode, eval=FALSE}
```




<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedEvolution.html")
```
