---
title: "Heatmap with smoothing - LatticeExtra"
descriptionMeta: "The latticeExtra package allows to build a heatmap with smoothing. Here is how with reproducible code."
descriptionTop: "The `latticeExtra` package allows to build a [heatmap](heatmap.html) with smoothing. Here is how with reproducible code."
sectionText: "Heatmap section"
sectionLink: "heatmap.html"
DataToVizText: "Data to Viz"
DataToVizLink: "data-to-viz.com/graph/heatmap.html"
url: "201-levelplot-with-latticeextra"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 100px">








<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

The levelplot function of lattice allows to deal with 3 numeric variables as shown in the heatmap section of the gallery.

Here, the idea is to plot data points as circles using `panel.levelplot.points` to get a scatterplot. Then, a layer is added using `panel.2dsmoother` to show the general distribution of the third numeric variable.
</div>


<div class = "col-md-6  col-sm-12">

```{r thecode, echo=FALSE, out.width = "100%", fig.height=7}
# library
library(latticeExtra) 
 
# create data
set.seed(1) 
data <- data.frame(x = rnorm(100), y = rnorm(100)) 
data$z <- with(data, x * y + rnorm(100, sd = 1)) 
 
# showing data points on the same color scale 
levelplot(z ~ x * y, data, 
          panel = panel.levelplot.points, cex = 1.2
    ) + 
    layer_(panel.2dsmoother(..., n = 200))
```
</div>
</div>



```{r thecode, eval=FALSE}
```

























<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedCorrelation.html")
```
