---
title: "Most basic barplot"
descriptionMeta: "This post describes how to build a basic barplot with R, without any packages. Reproducible code and explanation are provided."
descriptionTop: "This post describes how to build a basic [barplot](barplot.html) with R, without any packages, using the `barplot()` function."
sectionText: "Barchart section"
sectionLink: "barplot.html"
DataToVizText: "Barplot tips"
DataToVizLink: "data-to-viz.com/graph/barplot.html"
url: "208-basic-barplot"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 100px">





<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

In R, a [barplot](barplot.html) is computed using the `barplot()` function. 

Here is the most basic example you can do. The input data is a data frame with 2 columns. `value` is used for bar height, `name` is used as category label.

<u>Note:</u> read more to

- [Customize](209-the-options-of-barplot.html) your barplot
- Do it with [ggplot2](barplot.html)

</div>


<div class = "col-md-6  col-sm-12">

```{r thecode, echo=FALSE, out.width = "100%", fig.height=7}
# create dummy data
data <- data.frame(
  name=letters[1:5],
  value=sample(seq(4,15),5)
)

# The most basic barplot you can do:
barplot(height=data$value, names=data$name)
```
</div>
</div>



```{r thecode, eval=FALSE}
```













<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedRanking.html")
```
