---
title: "Basic density chart with ggplot2"
descriptionMeta: "Learn how to build a basic density chart with ggplot2. Reproducible R code is provided."
descriptionTop: "A [density plot](https://www.data-to-viz.com/graph/density.html) is a representation of the distribution of a numeric variable. It is a smoothed version of the [histogram](histogram.html) and is used in the same kind of situation. Here is a basic example built with the [ggplot2](ggplot2.html) library."
sectionText: "Density Section"
sectionLink: "density.html"
DataToVizText: "Density theory"
DataToVizLink: "data-to-viz.com/graph/density.html"
url: "21-distribution-plot-using-ggplot2.html"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"

---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```


<div class="container" style="padding-top: 100px">






<div class = "row">
  
<div class = "col-md-5  col-sm-12 align-self-center">

Density plots are built in ggplot2 thanks to the `geom_density` geom. Only one numeric variable is need as input.

</div>
  
<div class = "col-md-7  col-sm-12">
```{r, echo=FALSE, out.width = "85%", fig.align='center'}
# Libraries
library(ggplot2)
library(dplyr)

# Load dataset from github
data <- read.table("https://raw.githubusercontent.com/holtzy/data_to_viz/master/Example_dataset/1_OneNum.csv", header=TRUE)

# Make the histogram
data %>%
  filter( price<300 ) %>%
  ggplot( aes(x=price)) +
    geom_density(fill="#69b3a2", color="#e9ecef", alpha=0.8)
```
</div>
</div>

```{r, eval=FALSE}
# Libraries
library(ggplot2)
library(dplyr)

# Load dataset from github
data <- read.table("https://raw.githubusercontent.com/holtzy/data_to_viz/master/Example_dataset/1_OneNum.csv", header=TRUE)

# Make the histogram
data %>%
  filter( price<300 ) %>%
  ggplot( aes(x=price)) +
    geom_density(fill="#69b3a2", color="#e9ecef", alpha=0.8)
```


# Custom with `theme_ipsum`
***


<div class = "row">
  
<div class = "col-md-5  col-sm-12 align-self-center">

The `hrbrthemes` package offer a set of pre-built themes for your charts. I am personnaly a big fan of the `theme_ipsum`: easy to use and makes your chart look more professional:

</div>
  
<div class = "col-md-7  col-sm-12">
```{r, echo=FALSE, out.width = "85%", fig.align='center'}
# Libraries
library(ggplot2)
library(dplyr)
library(hrbrthemes)

# Load dataset from github
data <- read.table("https://raw.githubusercontent.com/holtzy/data_to_viz/master/Example_dataset/1_OneNum.csv", header=TRUE)

# Make the histogram
data %>%
  filter( price<300 ) %>%
  ggplot( aes(x=price)) +
    geom_density(fill="#69b3a2", color="#e9ecef", alpha=0.8) +
    ggtitle("Night price distribution of Airbnb appartements") +
    theme_ipsum()
```
</div>
</div>

```{r, eval=FALSE}
# Libraries
library(ggplot2)
library(dplyr)
library(hrbrthemes)

# Load dataset from github
data <- read.table("https://raw.githubusercontent.com/holtzy/data_to_viz/master/Example_dataset/1_OneNum.csv", header=TRUE)

# Make the histogram
data %>%
  filter( price<300 ) %>%
  ggplot( aes(x=price)) +
    geom_density(fill="#69b3a2", color="#e9ecef", alpha=0.8) +
    ggtitle("Night price distribution of Airbnb appartements") +
    theme_ipsum()
```








<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedDistribution.html")
```







