---
title: "Display several chord diagrams on same figure"
descriptionMeta: "Here is a trick to display several chord diagrams on the same figure, using R and the circlize package."
descriptionTop: "Here is a trick to display several chord diagrams on the same figure, using R and the circlize package."
sectionText: "Chord section"
sectionLink: "chord-diagram.html"
DataToVizText: "Data to Viz"
DataToVizLink: "data-to-viz.com/graph/chord.html"
url: "229-several-circular-plots-in-a-figure"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 80px">



<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

To arrange several circular charts in the same layout, simply use the `layout()` function as shown below. 

This example comes from the circlize package [vignette](https://jokergoo.github.io/circlize_book/book/).

</div>


<div class = "col-md-6  col-sm-12">

```{r thecode, echo=FALSE, out.width = "100%", fig.height=7}
# library
library(circlize)
# Arrange the layout
layout(matrix(1:9, 3, 3)) 
 
# A loop to create 9 circular plots
for(i in 1:9) {
    par(mar = c(0.5, 0.5, 0.5, 0.5), bg=rgb(1,1,1,0.1) )
    factors = 1:8
    circos.par(cell.padding = c(0, 0, 0, 0)) 
    circos.initialize(factors, xlim = c(0, 1)) 
    circos.trackPlotRegion(ylim = c(0, 1), track.height = 0.05, bg.col = rand_color(8), bg.border = NA ) 
 
    # add links
    for(i in 1:20) {
        se = sample(1:8, 2)
        circos.link(se[1], runif(2), se[2], runif(2), col = rand_color(1, transparency = 0.4)) 
        
    }
    circos.clear()
}
```
</div>
</div>



```{r thecode, eval=FALSE}
```















<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedFlow.html")
```
