---
title: "Treemap with subgroups"
descriptionMeta: "This post explains how to build a treemap with subgroups in R. It uses the treemap package, provides reproducible code and explains how input data must be formatted."
descriptionTop: "This post explains how to build a [treemap](treemap.html) with subgroups in `R`. It uses the `treemap` package, provides reproducible code and explains how input data must be formatted."
sectionText: "Treemap section"
sectionLink: "treemap.html"
DataToVizText: "Data to Viz"
DataToVizLink: "data-to-viz.com/graph/treemap.html"
url: "235-treemap-with-subgroups"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 100px">




<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

This is a [treemap](treemap.html) with several levels. We have 3 groups, each containing several subgroups. Each subgroup has a value which we map to an area.

In the `index` argument, you need to specify levels in the order of importance: group > subgroup > sub-subgroup.

<u>Note</u>: If you have one level of grouping only, see chart [#234](234-a-very-basic-treemap.html)

<u>Note</u>: Showing more than 2 levels often result in a cluttered and unredable figure. Why not considering an [interactive version](237-interactive-treemap.html)?

</div>


<div class = "col-md-6  col-sm-12">

```{r thecode, echo=FALSE, out.width = "100%", fig.height=7}
# library
library(treemap)
 
# Build Dataset
group <- c(rep("group-1",4),rep("group-2",2),rep("group-3",3))
subgroup <- paste("subgroup" , c(1,2,3,4,1,2,1,2,3), sep="-")
value <- c(13,5,22,12,11,7,3,1,23)
data <- data.frame(group,subgroup,value)
 
# treemap
treemap(data,
            index=c("group","subgroup"),
            vSize="value",
            type="index"
            ) 
```
</div>
</div>



```{r thecode, eval=FALSE}
```









<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedPartOfWhole.html")
```
