---
title: "Histogram without border"
descriptionMeta: "This post explains how to get rid of histograms border in Basic R."
descriptionTop: "This posts explains how to get rid of histograms border in Basic R. It is purely about appearance preferences."
sectionText: "Histogram Section"
sectionLink: "histogram.html"
DataToVizText: "About histogram"
DataToVizLink: "data-to-viz.com/graph/histogram.html"
url: "82-boxplot-on-top-of-histogram.html"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 80px">




<div class = "row">
  
<div class = "col-md-6  col-sm-12 align-self-center">

Basically, you just need to add `border=F` to the `hist` function to remove the border of histogram bars.
</div>

  
<div class = "col-md-6  col-sm-12">

```{r, echo=FALSE, out.width = "100%", fig.height=7}
# Create data 
my_variable=c(rnorm(1000 , 0 , 2) , rnorm(1000 , 9 , 2))
 
# Draw the histogram with border=F
hist(my_variable , breaks=40 , col=rgb(0.2,0.8,0.5,0.5) , border=F , main="")
```
</div>
</div>


```{r eval=FALSE}
# Create data 
my_variable=c(rnorm(1000 , 0 , 2) , rnorm(1000 , 9 , 2))
 
# Draw the histogram with border=F
hist(my_variable , breaks=40 , col=rgb(0.2,0.8,0.5,0.5) , border=F , main="")
```


<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedDistribution.html")
```







