---
title: "Basic  ggplot2 boxplot"
descriptionMeta: "The basics of boxplot with ggplot2: reproducible R code and explanation provided."
descriptionTop: "A [boxplot](boxplot.html) summarizes the distribution of a continuous variable. It displays its median, its first and third quartiles and its outliers. Main caveat is that the underlying distribution is [hidden](https://www.data-to-viz.com/caveat/boxplot.html). This page explains how to build a basic  boxplot with [ggplot2](ggplot2.html)."
sectionText: "Boxplot Section"
sectionLink: "boxplot.html"
DataToVizText: "Boxplot pitfalls"
DataToVizLink: "data-to-viz.com/caveat/boxplot.html"
url: "262-basic-boxplot-with-ggplot2"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 80px">




<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

The [ggplot2 library](ggplot2.html) allows to make a [boxplot](boxplot.html) using `geom_boxplot()`. You have to specify a quantitative variable for the Y axis, and a qualitative variable for the X axis ( a group).

</div>


<div class = "col-md-6  col-sm-12">

```{r, echo=FALSE, out.width = "100%", fig.height=7}
# Load ggplot2
library(ggplot2)
 
# The mtcars dataset is natively available
# head(mtcars)
 
# A really basic boxplot.
ggplot(mtcars, aes(x=as.factor(cyl), y=mpg)) + 
    geom_boxplot(fill="slateblue", alpha=0.2) + 
    xlab("cyl")
```
</div>
</div>


```{r eval=FALSE}
# Load ggplot2
library(ggplot2)
 
# The mtcars dataset is natively available
# head(mtcars)
 
# A really basic boxplot.
ggplot(mtcars, aes(x=as.factor(cyl), y=mpg)) + 
    geom_boxplot(fill="slateblue", alpha=0.2) + 
    xlab("cyl")
```


<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedDistribution.html")
```
