---
title: "Ggplot2 boxplot parameters"
descriptionMeta: "Description of the main options allowing to custom a ggplot2 boxplot."
descriptionTop: "A [boxplot](boxplot.html) summarizes the distribution of a continuous variable. The [ggplot2](ggplot2.html) library allows to build it thanks to the `geom_boxplot` function. This function offers several options to custom its appearance and this post is dedicated to them."
sectionText: "Boxplot Section"
sectionLink: "boxplot.html"
DataToVizText: "Boxplot pitfalls"
DataToVizLink: "data-to-viz.com/caveat/boxplot.html"
url: "263-ggplot2-boxplot-parameters"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 80px">




<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

This chart extends the previous most basic boxplot described in [graph #262](262-basic-boxplot-with-ggplot2.html).  
 
It describes the option you can apply to the `geom_boxplot()` function to custom the general chart appearance.

<u>Note on notches</u>: useful to compare groups: if no overlap between 2 groups, medians are significantly different.

</div>


<div class = "col-md-6  col-sm-12">

```{r, echo=FALSE, out.width = "100%", fig.height=7}
# Load ggplot2
library(ggplot2)
 
# The mpg dataset is natively available
#head(mpg)
 
# geom_boxplot proposes several arguments to custom appearance
ggplot(mpg, aes(x=class, y=hwy)) + 
    geom_boxplot(
        
        # custom boxes
        color="blue",
        fill="blue",
        alpha=0.2,
        
        # Notch?
        notch=TRUE,
        notchwidth = 0.8,
        
        # custom outliers
        outlier.colour="red",
        outlier.fill="red",
        outlier.size=3
    
    ) +
    xlab("")
```
</div>
</div>


```{r eval=FALSE}
# Load ggplot2
library(ggplot2)
 
# The mpg dataset is natively available
#head(mpg)
 
# geom_boxplot proposes several arguments to custom appearance
ggplot(mpg, aes(x=class, y=hwy)) + 
    geom_boxplot(
        
        # custom boxes
        color="blue",
        fill="blue",
        alpha=0.2,
        
        # Notch?
        notch=TRUE,
        notchwidth = 0.8,
        
        # custom outliers
        outlier.colour="red",
        outlier.fill="red",
        outlier.size=3
    
    )
```


<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedDistribution.html")
```
