---
title: "ggplot2 boxplot with mean value"
descriptionMeta: "This post explains how to build a boxplot with ggplot2, adding a marker for the mean of each group."
descriptionTop: "A [boxplot](boxplot.html) summarizes the distribution of a continuous variable and notably displays the median of each group. This post explains how to add the value of the mean for each group with [ggplot2](ggplot2-package.html)."
sectionText: "Boxplot Section"
sectionLink: "boxplot.html"
DataToVizText: "Boxplot pitfalls"
DataToVizLink: "data-to-viz.com/caveat/boxplot.html"
url: "269-ggplot2-boxplot-with-average-value"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 100px">




<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

[Ggplot2](ggplot2-package.html) allows to show the average value of each group using the `stat_summary()` function. No more need to calculate your mean values before plotting.

</div>


<div class = "col-md-6  col-sm-12">

```{r, echo=FALSE, out.width = "100%", fig.height=7}
# Library
library(ggplot2)
 
# create data
names=c(rep("A", 20) , rep("B", 8) , rep("C", 30), rep("D", 80))
value=c( sample(2:5, 20 , replace=T) , sample(4:10, 8 , replace=T), sample(1:7, 30 , replace=T), sample(3:8, 80 , replace=T) )
data=data.frame(names,value)
 
# plot
ggplot(data, aes(x=names, y=value, fill=names)) +
    geom_boxplot(alpha=0.7) +
    stat_summary(fun.y=mean, geom="point", shape=20, size=14, color="red", fill="red") +
    theme(legend.position="none") +
    scale_fill_brewer(palette="Set1")
```
</div>
</div>



```{r, eval=FALSE}
# Library
library(ggplot2)
 
# create data
names=c(rep("A", 20) , rep("B", 8) , rep("C", 30), rep("D", 80))
value=c( sample(2:5, 20 , replace=T) , sample(4:10, 8 , replace=T), sample(1:7, 30 , replace=T), sample(3:8, 80 , replace=T) )
data=data.frame(names,value)
 
# plot
p <- ggplot(data, aes(x=names, y=value, fill=names)) +
    geom_boxplot(alpha=0.7) +
    stat_summary(fun.y=mean, geom="point", shape=20, size=14, color="red", fill="red") +
    theme(legend.position="none") +
    scale_fill_brewer(palette="Set1")
```

<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedDistribution.html")
```
