---
title: "ggplot2 scatterplot with rug"
descriptionMeta: "This post demonstrates how to build a scatterplot with rug with R and ggplot2. Adding rug gives insight about variable distribution and is especially helpful when overlapping happens."
descriptionTop: "This post demonstrates how to build a [scatterplot](scatterplot.html) with rug with `R` and [ggplot2](ggplot2.html). Adding rug gives insight about variable distribution and is especially helpful when markers overlap."
sectionText: "Scatter section"
sectionLink: "scatterplot.html"
DataToVizText: "About overplotting"
DataToVizLink: "data-to-viz.com/caveat/overplotting.html"
url: "276-scatterplot-with-rug-ggplot2"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container">



# Adding text with `geom_text()`
***

<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

A [scatterplot](scatterplot.html) displays the relationship between 2 numeric variables. You can easily add rug on X and Y axis thanks to the `geom_rug()` function to illustrate the distribution of dots.

Note you can as well add [marginal plots](277-marginal-histogram-for-ggplot2.html) to show these distributions.
</div>


<div class = "col-md-6  col-sm-12">

```{r thecode, echo=FALSE, out.width = "100%", fig.height=7}
# library
library(ggplot2)
 
# Iris dataset
head(iris)
 
# plot
ggplot(data=iris, aes(x=Sepal.Length, Petal.Length)) + 
  geom_point() + 
  geom_rug(col="steelblue",alpha=0.1, size=1.5)
```
</div>
</div>



```{r thecode, eval=FALSE}
```









<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedCorrelation.html")
```
