---
title: "Waffer map"
descriptionMeta: "A wafer map is used to visualize the performance of a semiconductor device on a substrate. Learn how to draw it with R and the tidyverse."
descriptionTop: "A wafer map is used to visualize the performance of a semiconductor device on a substrate. Learn how to draw it with `R` and the [tidyverse](ggplot2.html)."
sectionText: "Heatmap section"
sectionLink: "heatmap.html"
DataToVizText: "Data to Viz"
DataToVizLink: "data-to-viz.com/graph/heatmap.html"
url: "285-waffer-map"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 100px">




```{r thecode, echo=FALSE, fig.width = 8, fig.height=7, fig.align="center"}
# load data
madeUp=read.table("https://raw.githubusercontent.com/holtzy/R-graph-gallery/master/DATA/madeUp.csv", sep=",", header=T)
 
# load libraries
library(tidyverse)
 
# Prepare data 
theData <- madeUp %>% 
 group_by(X.Axis, Y.Axis, Group) %>% 
 dplyr::summarize(statistic=mean(randVals, na.rm = TRUE))
 
# plot
ggplot(theData, aes(X.Axis, Y.Axis)) +
	
	coord_cartesian(xlim = c(0,20), ylim = c(0,20)) +
	scale_x_continuous(breaks = seq(0,20)) +
	scale_y_continuous(breaks = seq(0,20))+
	
	geom_tile(aes(fill=statistic))+
	guides(fill=guide_legend(title='Legend'))+
	
	theme(
		panel.background = element_rect(fill= 'white', color = 'white'),
		panel.grid.major = element_line(color='#E0E0E0'),
		panel.grid.minor = element_line(color='#E0E0E0')
		)+
		
	ggtitle('Wafer Map')+
	facet_wrap(~Group)+
	scale_fill_gradientn(colors = rainbow(100))
```


A [wafer map](heatmap.html) is used to visualize the performance of a semiconductor device on a substrate. Each rectangle represents an individual semiconductor chip and its colour or pattern can represent some property of the chip.

Data used as input in this examples are available here.

Thanks to to Alex Pavlides from [Mango Solution](https://www.mango-solutions.com/) for this submission!


```{r thecode, eval=FALSE}
```








<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedCorrelation.html")
```
