---
title: "3d surface plot with R and plotly"
descriptionMeta: "A surface plot displays the evolution of a numeric variable on a grid. The R plotly package offers some great functions to build that kind of chart."
descriptionTop: "A surface plot displays the evolution of a numeric variable on a grid. The R plotly package offers some great functions to build that kind of chart."
sectionText: "3d Section"
sectionLink: "3d.html"
DataToVizText: "3d: warning"
DataToVizLink: "data-to-viz.com/caveat/3d.html"
url: "3d-surface-plot"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container">




# Most basic bubble chart with `geom_point()`
***

<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

[Plotly](plotly.html) allows to build charts thanks to it `plot_ly()` function. It offers several `type` option. `surface` allows to make surface plots and expect a matrix as input.

Rows and columns actually describe a grid, and the cell value will be mapped to the surface height. Once the chart is done, you can hover and zoom on the chart for more details.

</div>


<div class = "col-md-6  col-sm-12">

<center><iframe src="HtmlWidget/3dSurface.html" height="700" width="700" style="border:none;"></iframe></center>

</div>
</div>




```{r, eval=FALSE}
# Library
library(plotly)

# Data: volcano is provided by plotly

# Plot
p <- plot_ly(z = volcano, type = "surface")
p 

# save the widget
# library(htmlwidgets)
# saveWidget(p, file=paste0( getwd(), "/HtmlWidget/3dSurface.html"))
```






```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedOther.html")
```
