---
title: "Get a long color palette with RColorBrewer"
descriptionMeta: "This post describes how to get a long color palette with R and the RColorBrewer package."
descriptionTop: "This post describes how to get a long color palette with R and the RColorBrewer package."
sectionText: "Base R color Section"
sectionLink: "colors.html"
DataToVizText: "About line chart"
DataToVizLink: "data-to-viz.com/graph/line.html"
url: "40-rcolorbrewer-get-a-longer-palette"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 80px">



<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

The `RColorBrewer` package is a great tool when it comes to build a color palette with R. However, the default palettes give only about 10 different colors. Here is a tip to get more colors in a graph, still using this useful package. Basically, it relies on the `colorRampPalette()` function to extand a first palette.
 
 
<u>Note</u>: visit [this post](package/rColorBrewer.html) for a complete list of the available palettes.

</div>

<br><br>

<div class = "col-md-6  col-sm-12">

```{r thecode, echo=FALSE, out.width = "100%", fig.height=7}
# No margin
par(mar=c(0,0,1,0))

# Load RColorBrewer
library(RColorBrewer)

# Classic palette BuPu, with 4 colors
coul <- brewer.pal(4, "PuOr") 

# Add more colors to this palette :
coul <- colorRampPalette(coul)(25)

# Plot it
pie(rep(1, length(coul)), col = coul , main="") 
```

</div>
</div>


```{r thecode, eval=FALSE}
```




<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedOther.html")
```
