---
title: "An overview of color numbers in R"
descriptionMeta: "This post displays more than 200 colors that can be called by a number in R. In case you're struggling to find the one that suits you the best."
descriptionTop: "This post displays more than 200 colors that can be called by a number in `R`. In case you're struggling to find the one that suits you the best."
sectionText: "Color Section"
sectionLink: "ggplot2-color.html"
DataToVizText: "About line chart"
DataToVizLink: "data-to-viz.com/graph/line.html"
url: "41-value-of-the-col-function"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 80px">



<div class = "row">

<div class = "col-md-4  col-sm-12 align-self-center">

In `R` you can call colors by their numbers. This picture shows corespondances between numbers and colors.

For example, if you call `col=colors()[143]`, You will get a kind of yellow.

</div>

<br><br>

<div class = "col-md-8  col-sm-12">

```{r thecode, echo=FALSE, out.width = "100%", fig.height=8}
par(mar=c(0,0,0,0))
plot(0, 0, type = "n", xlim = c(0, 1), ylim = c(0, 1), axes = FALSE, xlab = "", ylab = "")

# Parameters
line <- 31
col <- 21

# Rectangles
rect( rep((0:(col - 1)/col),line) ,  sort(rep((0:(line - 1)/line),col),decreasing=T) , rep((1:col/col),line) , sort(rep((1:line/line),col),decreasing=T),  
       border = "light gray" , col=colors()[seq(1,651)])

# Text
text( rep((0:(col - 1)/col),line)+0.02 ,  sort(rep((0:(line - 1)/line),col),decreasing=T)+0.01 , seq(1,651)  , cex=0.5)
```

</div>
</div>


```{r thecode, eval=FALSE}
```




<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedOther.html")
```
