---
title: "An overview of color names in R"
descriptionMeta: "This post displays more than 100 colors that can be called by a name in R. In case you're struggling the one that suits you the best."
descriptionTop: "This post displays more than 100 colors that can be called by a name in R. In case you're struggling the one that suits you the best."
sectionText: "Color Section"
sectionLink: "ggplot2-color.html"
DataToVizText: "About line chart"
DataToVizLink: "data-to-viz.com/graph/line.html"
url: "42-colors-names"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 80px">



<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

It is possible to call a color by its name in `R`. Here is an overview of the main colors offered. 

Note that you can see a complete list of the 657 colors typing `colors()`.

See the [color section](ggplot2-color.html) of the gallery for more color calling options.

</div>

<br><br>

<div class = "col-md-6  col-sm-12">

```{r thecode, echo=FALSE, out.width = "100%", fig.height=8}
# No margin around chart
par(mar=c(0,0,0,0))

# Empty chart
plot(0, 0, type = "n", xlim = c(0, 1), ylim = c(0, 1), axes = FALSE, xlab = "", ylab = "")

# Settings
line <- 25
col <- 5

# Add color background
rect(  
  rep((0:(col - 1)/col),line) ,  
  sort(rep((0:(line - 1)/line),col),decreasing=T),   
  rep((1:col/col),line) , 
  sort(rep((1:line/line),col),decreasing=T),  
  border = "white" , 
  col=colors()[seq(1,line*col)])

# Color names
text(  
  rep((0:(col - 1)/col),line)+0.1 ,  
  sort(rep((0:(line - 1)/line),col),decreasing=T)+0.015 , 
  colors()[seq(1,line*col)]  , 
  cex=1)
```

</div>
</div>


```{r thecode, eval=FALSE}
```




<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedOther.html")
```
