---
title: "Nifty graph: a 3d imitation with R"
descriptionMeta: "A graph by Matt Asher showing probability function in a data art fashion."
descriptionTop: "A graph by Matt Asher showing probability function in a data art fashion."
sectionText: "3d Section"
sectionLink: "3d.html"
DataToVizText: "3d: warning"
DataToVizLink: "data-to-viz.com/caveat/3d.html"
url: "59-nifty-graph"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 80px">



<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

This graph comes from the probability and statistics blog of [Matt Asher](http://www.statisticsblog.com/category/plot/page/2/)
Thanks for this contribution !

</div>


<div class = "col-md-6  col-sm-12">

```{r thecode, echo=FALSE, out.width = "100%", fig.height=7}
moxbuller = function(n) {   
    u = runif(n)   
    v = runif(n)   
    x = cos(2*pi*u)*sqrt(-2*log(v))  
    y = sin(2*pi*v)*sqrt(-2*log(u))
    r = list(x=x, y=y)
    return(r) 
}
r = moxbuller(50000) 
par(bg="black") 
par(mar=c(0,0,0,0)) 
plot(r$x,r$y, pch=".", col="blue", cex=1.2)
```

</div>
</div>


```{r thecode, eval=FALSE}
```




<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedOther.html")
```
