---
title: "Control box type with the bty option"
descriptionMeta: "The bty option of the par() function allows to control box style of base R charts. Examples with code and explanation."
descriptionTop: "The `bty` option of the `par()` function allows to control the box style of base R charts. This post provides a few examples illustrating how this option works."
sectionText: "Boxplot Section"
sectionLink: "boxplot.html"
DataToVizText: "Boxplot pitfalls"
DataToVizLink: "data-to-viz.com/caveat/boxplot.html"
url: "73-box-style-with-the-bty-function"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 100px">




<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

The `bty` option of the `par()` function allows to custom the box around the plot.

Several letters are possible. Shape of the letter represents the boundaries: 

- `o`: complete box (default parameter), 
- `n`: no box
- `7`: top + right
- `L`: bottom + left
- `C`: top + left + bottom
- `U`: left + bottom + right

</div>


<div class = "col-md-6  col-sm-12">

```{r, echo=FALSE, out.width = "100%", fig.height=7}
# Cut the screen in 4 parts
par(mfrow=c(2,2))
 
#Create data
a=seq(1,29)+4*runif(29,0.4)
b=seq(1,29)^2+runif(29,0.98)
 
# First graph
par(bty="l")
boxplot(a , col="#69b3a2" , xlab="bottom & left box")
# Second
par(bty="o")
boxplot(b , col="#69b3a2" , xlab="complete box", horizontal=TRUE)
# Third
par(bty="c")
boxplot(a , col="#69b3a2" , xlab="up & bottom & left box", width=0.5)
# Fourth
par(bty="n")
boxplot(a , col="#69b3a2" , xlab="no box")
```
</div>
</div>



```{r, eval=FALSE}
# Cut the screen in 4 parts
par(mfrow=c(2,2))
 
#Create data
a=seq(1,29)+4*runif(29,0.4)
b=seq(1,29)^2+runif(29,0.98)
 
# First graph
par(bty="l")
boxplot(a , col="#69b3a2" , xlab="bottom & left box")
# Second
par(bty="o")
boxplot(b , col="#69b3a2" , xlab="complete box", horizontal=TRUE)
# Third
par(bty="c")
boxplot(a , col="#69b3a2" , xlab="up & bottom & left box", width=0.5)
# Fourth
par(bty="n")
boxplot(a , col="#69b3a2" , xlab="no box")
```



<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedDistribution.html")
```
