---
title: "The split_screen() function of R"
descriptionMeta: "This document explains how to use the split_screen function of R to divide your device in several parts, one for each chart."
descriptionTop: "This document explains how to use the `split_screen()` function of R to divide your device in several parts, one for each chart."
sectionText: "Scatter section"
sectionLink: "scatterplot.html"
DataToVizText: "Data to Viz"
DataToVizLink: "data-to-viz.com/graph/scatter.html"
url: "76_split_screen_function"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 100px">



<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

The `split_screen()` function allows to divide the window in several chart sections.

However, I personnaly believe that  

- the [mfrow method](71-split-screen-with-par-mfrow.html) is more adapted for simple layouts
- the [layout function](75-split-screen-with-layout.html) is better for complex layouts.

</div>


<div class = "col-md-6  col-sm-12">

```{r thecode, echo=FALSE, out.width = "100%", fig.height=7}
#Create data
a <- seq(1,29)+4*runif(29,0.4)
b <- seq(1,29)^2+runif(29,0.98)
 
# I divide the screen in 2 line and 1 column only
my_screen_step1 <- split.screen(c(2, 1))
 
# I add one graph on the screen number 1 which is on top :
screen(my_screen_step1[1])
plot( a,b , pch=20 , xlab="value of a" , cex=3 , col=rgb(0.4,0.9,0.8,0.5) )
 
 
# I divide the second screen in 2 columns :
my_screen_step2 <- split.screen(c(1, 2), screen = my_screen_step1[2])
screen(my_screen_step2[1])
hist(a, border=F , col=rgb(0.2,0.2,0.8,0.7) , main="" , xlab="distribution of a")
screen(my_screen_step2[2])
hist(b, border=F , col=rgb(0.8,0.2,0.8,0.7) , main="" ,  xlab="distribution of b")
```
</div>
</div>



```{r thecode, eval=FALSE}
```









<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedCorrelation.html")
```
