---
title: "Reversed Y axis in base R"
descriptionMeta: "This post explains how to reverse the Y axis on a chart with R. It uses a line chart as example and provides the reproducible code."
descriptionTop: "This post explains how to reverse the Y axis on a chart with `R`. It uses a [line chart](line-plot.html) as example and provides the reproducible code."
sectionText: "Line chart Section"
sectionLink: "line-plot.html"
DataToVizText: "About line chart"
DataToVizLink: "data-to-viz.com/graph/line.html"
url: "77-turn-y-axis-upside-down"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 80px">



<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

It is a common need in dataviz to flip the Y axis upside down. In base R this is pretty easy to do: you just have to reverse the values of the `ylim` argument.

This can be done using this statement: `rev(range(y))` 

<u>Note</u>: be carefull, do not build a [counter-iintuitive](https://www.data-to-viz.com/caveat/counter_intuitive.html) chart

</div>


<div class = "col-md-6  col-sm-12">

```{r thecode, echo=FALSE, out.width = "100%", fig.height=7}
# Create data
x <- seq(1,29)^2+runif(29,0.98)
y <- abs(seq(1,29)+4*runif(29,0.4))

# Make the plotwith ylim in reverse
plot(y~x , ylim = rev(range(y)) ,
     lwd=4 , type="l" , bty="n" , ylab="value of y (decreasing)" , col=rgb(0.2,0.4,0.6,0.8) )

#Add the grey lines
abline(v=seq(0,900,100) , col="grey" , lwd=0.6)
```

</div>
</div>


```{r thecode, eval=FALSE}
```




<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedEvolution.html")
```
