---
title: "Barplot with variable width - ggplot2"
descriptionMeta: "This post explains how to draw a barplot with variable bar width using R and ggplot2. It can be useful to represent the sample size available behind each group."
descriptionTop: "This post explains how to draw a [barplot](barplot.html) with variable bar width using R and [ggplot2](ggplot2.html). It can be useful to represent the sample size available behind each group."
sectionText: "Barchart section"
sectionLink: "barplot.html"
DataToVizText: "Data to Viz"
DataToVizLink: "data-to-viz.com/graph/barplot.html"
url: "81-barplot-with-variable-width"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 100px">





<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

This example shows how to customize bar width in your [barchart](barplot.html). It can be used to show the sample size hidden between each category.

It is not possible to draw that kind of chart using `geom_bar()` directly. You need to compute manually the position of each bar extremity using the `cumsum()` function, and plot the result using `geom_rect()`.

<u>Note</u>: if you know what the distribution behind each bar is, don't do a barplot, [show it](https://www.data-to-viz.com/caveat/error_bar.html).

</div>


<div class = "col-md-6  col-sm-12">

```{r thecode, echo=FALSE, out.width = "100%", fig.height=7}
# Load ggplot2
library(ggplot2)
library(hrbrthemes) # for style

# make data
data <- data.frame(
  group=c("A ","B ","C ","D ") , 
  value=c(33,62,56,67) , 
  number_of_obs=c(100,500,459,342)
)
 
# Calculate the future positions on the x axis of each bar (left border, central position, right border)
data$right <- cumsum(data$number_of_obs) + 30*c(0:(nrow(data)-1))
data$left <- data$right - data$number_of_obs 
 
# Plot
ggplot(data, aes(ymin = 0)) + 
    geom_rect(aes(xmin = left, xmax = right, ymax = value, colour = group, fill = group)) +
    xlab("number of obs") + 
    ylab("value") +
    theme_ipsum() +
    theme(legend.position="none") 
```
</div>
</div>



```{r thecode, eval=FALSE}
```


















<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedRanking.html")
```
