---
title: "Boxplot on top of histogram"
descriptionMeta: "How to display a boxplot on top of a histogram in Base R."
descriptionTop: "A [histogram](https://www.data-to-viz.com/graph/histogram.html) displays the distribution of a numeric variable. This posts explains how to add a boxplot on top of a histogram in Basic R, without any package."
sectionText: "Histogram Section"
sectionLink: "histogram.html"
DataToVizText: "About histogram"
DataToVizLink: "data-to-viz.com/graph/histogram.html"
url: "82-boxplot-on-top-of-histogram.html"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container" style="padding-top: 80px">




<div class = "row">
  
<div class = "col-md-6  col-sm-12 align-self-center">

This example illustrates how to split the plotting window in base R thanks to the `layout function`. Contrary to the `par(mfrow=...)` solution, `layout()` allows greater control of panel parts.

Here a [boxplot](boxplot.html) is added on top of the [histogram](histogram.html), allowing to quickly observe summary statistics of the distribution.

</div>

  
<div class = "col-md-6  col-sm-12">

```{r, echo=FALSE, out.width = "100%", fig.height=7}
# Create data 
my_variable <- c( 
  rnorm(1000 , 0 , 2) , 
  rnorm(1000 , 9 , 2)
)

# Please Ignore, specific to a bug in the gallery
library(pacman)
pacman::p_unload(pacman::p_loaded(), character.only = TRUE)

# Layout to split the screen
layout(mat=matrix(c(1,2),2,1, byrow=TRUE),  height = c(1,8))
 
# Draw the boxplot and the histogram 
par(mar=c(0, 3.1, 1.1, 2.1))
boxplot(my_variable , horizontal=TRUE , ylim=c(-10,20), xaxt="n" , col=rgb(0.8,0.8,0,0.5) , frame=F)
par(mar=c(4, 3.1, 1.1, 2.1))
hist(my_variable , breaks=40 , col=rgb(0.2,0.8,0.5,0.5) , border=F , main="" , xlab="value of the variable", xlim=c(-10,20))
```
</div>
</div>


```{r eval=FALSE}
# Create data 
my_variable=c(rnorm(1000 , 0 , 2) , rnorm(1000 , 9 , 2))
 
# Layout to split the screen
layout(mat = matrix(c(1,2),2,1, byrow=TRUE),  height = c(1,8))
 
# Draw the boxplot and the histogram 
par(mar=c(0, 3.1, 1.1, 2.1))
boxplot(my_variable , horizontal=TRUE , ylim=c(-10,20), xaxt="n" , col=rgb(0.8,0.8,0,0.5) , frame=F)
par(mar=c(4, 3.1, 1.1, 2.1))
hist(my_variable , breaks=40 , col=rgb(0.2,0.8,0.5,0.5) , border=F , main="" , xlab="value of the variable", xlim=c(-10,20))
```


<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedDistribution.html")
```







