---
title: "Violin Plot with the vioplot package"
descriptionMeta: "Learn how to build a violin plot with R and the Vioplot library. Reproducible R code is provided."
descriptionTop: "[Violin plots](violin.html) are useful to compare the distribution of several groups. I strongly advise to use [ggplot2](95-violin-plot-with-ggplot2.html) to build them, but the `vioplot` library is an alternative in case you don't want to use the `tidyverse`."
sectionText: "Violin Section"
sectionLink: "violin.html"
DataToVizText: "Violin theory"
DataToVizLink: "data-to-viz.com/graph/violin.html"
url: "94-violin-plot.html"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"

---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```


<div class="container" style="padding-top: 100px">






<div class = "row">
  
<div class = "col-md-5  col-sm-12 align-self-center">

The `Vioplot` library builds the [violin plot](violin.html) as a boxplot with a rotated kernel density plot on each side. If you want to represent several groups, the trick is to use the `with` function as demonstrated below.

<u>Note</u>: consider using the [ggplot2 package](ggplot2.html) as shown in [graph #95](95-violin-plot-with-ggplot2).

</div>
  
<div class = "col-md-7  col-sm-12">
```{r, warning=FALSE, echo=FALSE, out.width = "100%", fig.width=5, fig.height=5}
# Load the vioplot library
library(vioplot)
 
# Create data
treatment <- c(rep("A", 40) , rep("B", 40) , rep("C", 40) )
value <- c( sample(2:5, 40 , replace=T) , sample(c(1:5,12:17), 40 , replace=T), sample(1:7, 40 , replace=T) )
data <- data.frame(treatment,value)
 
# Draw the plot
with(data , vioplot( 
  value[treatment=="A"] , value[treatment=="B"], value[treatment=="C"],  
  col=rgb(0.1,0.4,0.7,0.7) , names=c("A","B","C") 
))
```
</div>
</div>

```{r, eval=FALSE}
# Load the vioplot library
library(vioplot)
 
# Create data
treatment <- c(rep("A", 40) , rep("B", 40) , rep("C", 40) )
value <- c( sample(2:5, 40 , replace=T) , sample(c(1:5,12:17), 40 , replace=T), sample(1:7, 40 , replace=T) )
data <- data.frame(treatment,value)
 
# Draw the plot
with(data , vioplot( 
  value[treatment=="A"] , value[treatment=="B"], value[treatment=="C"],  
  col=rgb(0.1,0.4,0.7,0.7) , names=c("A","B","C") 
))
```










<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedDistribution.html")
```







