---
title: "Correlogram with the ellipse package"
descriptionMeta: "This post explains how to build a correlogram based on ellipses with the ellipse R package. It provides several reproducible examples with explanation and R code."
descriptionTop: "This post explains how to build a [correlogram](correlogram.html) based on ellipses with the `ellipse` R package. It provides several reproducible examples with explanation and `R` code."
sectionText: "Correlogram section"
sectionLink: "correlogram.html"
DataToVizText: "Data to Viz"
DataToVizLink: "data-to-viz.com/graph/correlogram.html"
url: "97-correlation-ellipses"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container">




# Scatterplot matrix with `ggpairs()`
***

<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

The `ellipse` package allows to build a correlogram thanks to the `plotcorr()` function.

First of all, you have to compute the correlation matrix of your dataset using the `cor()` function of R. Each correliation will be represented as an ellipse by the `plotcorr()` function. Color, shape and orientation depend on the correlation value.
</div>


<div class = "col-md-6  col-sm-12">

```{r thecode, echo=FALSE, out.width = "100%", fig.height=7}
# Libraries
library(ellipse)
library(RColorBrewer)
 
# Use of the mtcars data proposed by R
data <- cor(mtcars)
 
# Build a Pannel of 100 colors with Rcolor Brewer
my_colors <- brewer.pal(5, "Spectral")
my_colors <- colorRampPalette(my_colors)(100)
 
# Order the correlation matrix
ord <- order(data[1, ])
data_ord <- data[ord, ord]
plotcorr(data_ord , col=my_colors[data_ord*50+50] , mar=c(1,1,1,1)  )
```
</div>
</div>



```{r thecode, eval=FALSE}
```













<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedCorrelation.html")
```
