---
title: "Correlogram with the car package"
descriptionMeta: "This post explains how to build a scatterplot matrix with the car package. It provides several reproducible examples with explanation and R code."
descriptionTop: "This post explains how to build a [scatterplot matrix](correlogram.html) with the car package. It provides several reproducible examples with explanation and R code."
sectionText: "Correlogram section"
sectionLink: "correlogram.html"
DataToVizText: "Data to Viz"
DataToVizLink: "data-to-viz.com/graph/correlogram.html"
url: "99-scatterplot-matrix-car-package"
output:
  html_document:
      self_contained: false    
      mathjax: default
      lib_dir: libs
      template: template_rgg.html
      css: style.css
      toc: TRUE
      toc_float: TRUE
      toc_depth: 2
      df_print: "paged"
---


```{r global options, include = FALSE}
knitr::opts_chunk$set( warning=FALSE, message=FALSE)
```

<div class="container">




# Scatterplot matrix with the native `plot()` function
***

<div class = "row">

<div class = "col-md-6  col-sm-12 align-self-center">

This is a scatterplot matrix built with the `scatterplotMatrix()` function of the [car](https://cran.r-project.org/web/packages/car/index.html) package.

See more correlogram examples in the [dedicated section](correlogram.html).

Note the `|cyl` syntax: it means that categories available in the `cyl` variable must be represented distinctly (color, shape, size..).

</div>


<div class = "col-md-6  col-sm-12">

```{r thecode, echo=FALSE, out.width = "100%", fig.height=7}
# Packages
library(car)
library(RColorBrewer) # for the color palette

# Let's use the car dataset natively available in R
data <- mtcars

# Make the plot
my_colors <- brewer.pal(nlevels(as.factor(data$cyl)), "Set2")
scatterplotMatrix(~mpg+disp+drat|cyl, data=data , 
      reg.line="" , smoother="", col=my_colors , 
      smoother.args=list(col="grey") , cex=1.5 , 
      pch=c(15,16,17) , 
      main="Scatter plot with Three Cylinder Options"
      )
```
</div>
</div>



```{r thecode, eval=FALSE}
```












<!-- Close container -->
</div>




```{r, echo=FALSE}
htmltools::includeHTML("htmlChunkRelatedCorrelation.html")
```
